source 'https://rubygems.org'
ruby '2.6.4'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'sinatra-cross_origin'
gem 'rspec', '~>3.9'
gem 'unicorn', '~> 5.5', '>= 5.5.1'
gem 'mongo'
gem 'warden'
gem 'bcrypt'
